[MFLOG|0|2024-11-14T23:31:46.382956Z|runtime|80009833-0750-4191-9bd5-b889cd1d9ed8]2024/11/15 00:31:46 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[MFLOG|0|2024-11-14T23:31:46.429977Z|runtime|29052a5e-3f6f-40a9-ab07-54723fb81c5a]2024/11/15 00:31:46 WARNING mlflow.utils.autologging_utils: MLflow xgboost autologging is known to be compatible with 1.4.2 <= xgboost <= 2.1.1, but the installed version is 2.1.2. If you encounter errors during autologging, try upgrading / downgrading xgboost to a compatible version, or try upgrading MLflow.
[MFLOG|0|2024-11-14T23:31:46.444223Z|runtime|3f06594e-50c8-4c7d-a685-a78de1cf889d]2024/11/15 00:31:46 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
[MFLOG|0|2024-11-14T23:31:47.184561Z|runtime|95dcd5c7-6f00-4a5f-b80d-be920dfe4805]2024/11/15 00:31:47 ERROR mlflow.xgboost: Failed to log feature importance plot. XGBoost autologging will ignore the failure and continue. Exception: 
[MFLOG|0|2024-11-14T23:31:47.257613Z|runtime|2a617134-33b0-45c9-b742-a82b91ff26c1]Traceback (most recent call last):
[MFLOG|0|2024-11-14T23:31:47.257981Z|runtime|efaf8fce-f0d4-4459-a3ae-f28ad6d043a9]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/mlflow/xgboost/__init__.py", line 738, in train_impl
[MFLOG|0|2024-11-14T23:31:47.258408Z|runtime|a2ec60f6-ce59-4563-b651-ead766fb41af]    log_feature_importance_plot(features, importance, imp_type)
[MFLOG|0|2024-11-14T23:31:47.258725Z|runtime|fb11d180-a8bf-4a6f-bce2-eba6d3a93662]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/mlflow/xgboost/__init__.py", line 552, in log_feature_importance_plot
[MFLOG|0|2024-11-14T23:31:47.258935Z|runtime|69af8550-3592-4b21-aa04-83d68412964f]    import matplotlib.pyplot as plt
[MFLOG|0|2024-11-14T23:31:47.259064Z|runtime|75d5adcd-d5db-4be0-a035-38220bd0ca67]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/matplotlib/__init__.py", line 1270, in <module>
[MFLOG|0|2024-11-14T23:31:47.259296Z|runtime|249de5a1-9b2b-4cc3-8874-0fe22137e9b3]    rcParams['backend'] = os.environ.get('MPLBACKEND')
[MFLOG|0|2024-11-14T23:31:47.259439Z|runtime|f1b255a2-a1f8-434a-934e-4c3cf2d4f390]    ~~~~~~~~^^^^^^^^^^^
[MFLOG|0|2024-11-14T23:31:47.259525Z|runtime|e4397777-3b5c-4a19-a881-a7780bce40b8]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/matplotlib/__init__.py", line 738, in __setitem__
[MFLOG|0|2024-11-14T23:31:47.259609Z|runtime|8bbf6ed3-08d8-47d5-9e3a-fe6947648ca5]    raise ValueError(f"Key {key}: {ve}") from None
[MFLOG|0|2024-11-14T23:31:47.259874Z|runtime|4d1c9aca-3524-412f-ae98-6f07e440c947]ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
[MFLOG|0|2024-11-14T23:31:47.260173Z|runtime|0afe7088-a3f6-4298-a1ec-067af23ae967]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üèÉ View run cross-validation-fold-0 at: http://127.0.0.1:5000/#/experiments/0/runs/534e4b65625d43fd836aa21420d8d676.
[MFLOG|0|2024-11-14T23:31:47.305671Z|runtime|8704eb88-caa6-42f1-898d-828c78ba0c0c]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://127.0.0.1:5000/#/experiments/0.
[MFLOG|0|2024-11-14T23:31:47.306124Z|runtime|e7c85980-e443-4f20-ae40-d2104cf52301]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üèÉ View run 1731627072434019 at: http://127.0.0.1:5000/#/experiments/0/runs/0c8cd70bc11746339afadb8bd009d4f8.
[MFLOG|0|2024-11-14T23:31:57.769652Z|runtime|e64d0dcc-ceb4-43a5-bf66-f6487dbcc735]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://127.0.0.1:5000/#/experiments/0.
