[MFLOG|0|2024-11-14T23:31:46.385493Z|runtime|ab33fac3-2a24-4155-8f3a-509c428f95d3]2024/11/15 00:31:46 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[MFLOG|0|2024-11-14T23:31:46.429264Z|runtime|815114ce-1df1-4c60-9461-1256ec3ca203]2024/11/15 00:31:46 WARNING mlflow.utils.autologging_utils: MLflow xgboost autologging is known to be compatible with 1.4.2 <= xgboost <= 2.1.1, but the installed version is 2.1.2. If you encounter errors during autologging, try upgrading / downgrading xgboost to a compatible version, or try upgrading MLflow.
[MFLOG|0|2024-11-14T23:31:46.439682Z|runtime|afe4a064-016d-4373-9366-f2534fd5df55]2024/11/15 00:31:46 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
[MFLOG|0|2024-11-14T23:31:47.216235Z|runtime|c9543132-b025-488d-9f78-4e94c057613d]2024/11/15 00:31:47 ERROR mlflow.xgboost: Failed to log feature importance plot. XGBoost autologging will ignore the failure and continue. Exception: 
[MFLOG|0|2024-11-14T23:31:47.314508Z|runtime|a03a30a3-24e7-4c85-bd06-dd5bd719c15f]Traceback (most recent call last):
[MFLOG|0|2024-11-14T23:31:47.314750Z|runtime|4f0e1817-2213-4a42-b39a-90d99bd64104]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/mlflow/xgboost/__init__.py", line 738, in train_impl
[MFLOG|0|2024-11-14T23:31:47.314976Z|runtime|4cdc2c77-252f-4c6f-8805-a03dcb8b701c]    log_feature_importance_plot(features, importance, imp_type)
[MFLOG|0|2024-11-14T23:31:47.315103Z|runtime|1bb79952-3d40-4509-86ab-14fbcfdce536]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/mlflow/xgboost/__init__.py", line 552, in log_feature_importance_plot
[MFLOG|0|2024-11-14T23:31:47.315196Z|runtime|55415a52-b211-4d85-994b-65dafc457a7e]    import matplotlib.pyplot as plt
[MFLOG|0|2024-11-14T23:31:47.315278Z|runtime|456a7ccd-7ce4-4833-b886-345fc447994d]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/matplotlib/__init__.py", line 1270, in <module>
[MFLOG|0|2024-11-14T23:31:47.315358Z|runtime|6224c92a-4431-40ae-8ebd-4ff7c3f27d6e]    rcParams['backend'] = os.environ.get('MPLBACKEND')
[MFLOG|0|2024-11-14T23:31:47.315437Z|runtime|e7a50bcc-a953-443f-b2a4-409effe6551e]    ~~~~~~~~^^^^^^^^^^^
[MFLOG|0|2024-11-14T23:31:47.315944Z|runtime|bc187be9-84a2-4d22-8436-0c011244d7f1]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/matplotlib/__init__.py", line 738, in __setitem__
[MFLOG|0|2024-11-14T23:31:47.316118Z|runtime|3746b6e6-a711-4f59-8c5d-4c1fd1fa3a21]    raise ValueError(f"Key {key}: {ve}") from None
[MFLOG|0|2024-11-14T23:31:47.316225Z|runtime|04645825-45be-4671-9eda-2607028a03ea]ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
[MFLOG|0|2024-11-14T23:31:47.316463Z|runtime|499a86d2-2078-4d8e-8b36-752f69ccd0bb]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üèÉ View run cross-validation-fold-2 at: http://127.0.0.1:5000/#/experiments/0/runs/2660fd0cb18d499b8ff7c13706327a48.
[MFLOG|0|2024-11-14T23:31:47.366545Z|runtime|ab122835-51ca-4e9f-a294-941331aaaf60]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://127.0.0.1:5000/#/experiments/0.
[MFLOG|0|2024-11-14T23:31:47.370331Z|runtime|3e69f656-d107-484f-873b-16d0f0defa36]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üèÉ View run 1731627072434019 at: http://127.0.0.1:5000/#/experiments/0/runs/0c8cd70bc11746339afadb8bd009d4f8.
[MFLOG|0|2024-11-14T23:31:57.772218Z|runtime|01a3b22f-1a4a-4374-852a-97892751a6e7]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://127.0.0.1:5000/#/experiments/0.
