[MFLOG|0|2024-11-14T23:31:46.393938Z|runtime|d55c5ac3-c9a6-4f7d-842b-427066838268]2024/11/15 00:31:46 INFO mlflow.tracking.fluent: Autologging successfully enabled for sklearn.
[MFLOG|0|2024-11-14T23:31:46.431287Z|runtime|c7a7a1fc-2916-49cc-ba68-db4c913c9906]2024/11/15 00:31:46 WARNING mlflow.utils.autologging_utils: MLflow xgboost autologging is known to be compatible with 1.4.2 <= xgboost <= 2.1.1, but the installed version is 2.1.2. If you encounter errors during autologging, try upgrading / downgrading xgboost to a compatible version, or try upgrading MLflow.
[MFLOG|0|2024-11-14T23:31:46.443650Z|runtime|99328dfb-3019-4f77-804f-8e94bf1681dc]2024/11/15 00:31:46 INFO mlflow.tracking.fluent: Autologging successfully enabled for xgboost.
[MFLOG|0|2024-11-14T23:31:47.214544Z|runtime|a552ab47-b9b5-421b-a9a7-b019a6709418]2024/11/15 00:31:47 ERROR mlflow.xgboost: Failed to log feature importance plot. XGBoost autologging will ignore the failure and continue. Exception: 
[MFLOG|0|2024-11-14T23:31:47.305218Z|runtime|8efbf726-caf8-476c-87f8-9e4ec54aae68]Traceback (most recent call last):
[MFLOG|0|2024-11-14T23:31:47.305956Z|runtime|3b7f18da-fb0b-4a7a-a993-067367b34380]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/mlflow/xgboost/__init__.py", line 738, in train_impl
[MFLOG|0|2024-11-14T23:31:47.306251Z|runtime|d4f605ee-78d9-4643-a2bf-c44faa44ba89]    log_feature_importance_plot(features, importance, imp_type)
[MFLOG|0|2024-11-14T23:31:47.306328Z|runtime|03f6295c-2a72-4c10-9b96-cf702e40318e]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/mlflow/xgboost/__init__.py", line 552, in log_feature_importance_plot
[MFLOG|0|2024-11-14T23:31:47.306397Z|runtime|2282634e-7ad2-4308-992d-43695aba474b]    import matplotlib.pyplot as plt
[MFLOG|0|2024-11-14T23:31:47.306463Z|runtime|7b417dee-da4c-4723-9e34-986c31505f0d]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/matplotlib/__init__.py", line 1270, in <module>
[MFLOG|0|2024-11-14T23:31:47.306538Z|runtime|661101e6-61de-426f-8707-9e68f3cb2811]    rcParams['backend'] = os.environ.get('MPLBACKEND')
[MFLOG|0|2024-11-14T23:31:47.306607Z|runtime|b28f17b9-dd6e-43c8-ba48-10493e64bc42]    ~~~~~~~~^^^^^^^^^^^
[MFLOG|0|2024-11-14T23:31:47.306679Z|runtime|fcea81a0-f104-48de-8081-4edd06b8f0d7]  File "/Users/gabriel/micromamba/envs/metaflow/osx-arm64/e472752e21dbe09/lib/python3.12/site-packages/matplotlib/__init__.py", line 738, in __setitem__
[MFLOG|0|2024-11-14T23:31:47.306743Z|runtime|7ab18c72-e949-4df7-ae76-af3fd55bd30e]    raise ValueError(f"Key {key}: {ve}") from None
[MFLOG|0|2024-11-14T23:31:47.306807Z|runtime|c1e10cc8-140b-4693-b8f3-e33738add5fc]ValueError: Key backend: 'module://matplotlib_inline.backend_inline' is not a valid value for backend; supported values are ['gtk3agg', 'gtk3cairo', 'gtk4agg', 'gtk4cairo', 'macosx', 'nbagg', 'notebook', 'qtagg', 'qtcairo', 'qt5agg', 'qt5cairo', 'tkagg', 'tkcairo', 'webagg', 'wx', 'wxagg', 'wxcairo', 'agg', 'cairo', 'pdf', 'pgf', 'ps', 'svg', 'template']
[MFLOG|0|2024-11-14T23:31:47.306877Z|runtime|525b618a-7137-4a00-8033-c1862296121f]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üèÉ View run cross-validation-fold-3 at: http://127.0.0.1:5000/#/experiments/0/runs/d03a82798cc545129f194d07d9e740ea.
[MFLOG|0|2024-11-14T23:31:47.348155Z|runtime|d74c3184-544f-4660-ad46-7e25968bc011]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://127.0.0.1:5000/#/experiments/0.
[MFLOG|0|2024-11-14T23:31:47.348512Z|runtime|9ea654ab-006f-455f-891f-e6393eeb3281]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üèÉ View run 1731627072434019 at: http://127.0.0.1:5000/#/experiments/0/runs/0c8cd70bc11746339afadb8bd009d4f8.
[MFLOG|0|2024-11-14T23:31:57.765710Z|runtime|e0a22aa0-390d-4faf-bbc1-6470b99974b3]2024/11/15 00:31:47 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://127.0.0.1:5000/#/experiments/0.
